

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200

---

apiVersion: v1
kind: Endpoints
metadata:
  name: elasticsearch
  
subsets:
  - addresses:
    - ip: 10.0.0.4
    ports:
      - port: 9200